import argparse
import json
import os
import sys
from pathlib import Path

# Default model label for agy (see docs/AGY_PROGRAMMATIC.md for valid labels).
GEMINI_MODEL = os.environ.get("AGY_MODEL", "Gemini 3.5 Flash (Medium)")


def get_paths(project_name=None):
    """Returns the paths for task and usage files based on the project."""
    base = Path(".agent")
    if project_name:
        base = base / project_name
    
    return {
        "task_file": base / "swarm_tasks.md",
        "usage_file": Path(".agent/usage_stats.json"), # Usage is global
        "prompt_file": base / "architect_prompt.txt"
    }


def get_project_context():
    """Scans the project to give the Architect context."""
    # Simple recursive list of files (excluding .git, venv, etc)
    context = []
    for root, dirs, files in os.walk("."):
        if any(x in root for x in [".git", ".venv", "__pycache__", ".agent"]):
            continue
        for f in files:
            if f.endswith((".py", ".ps1", ".md", ".json")):
                context.append(os.path.join(root, f))
    return "\n".join(context[:50])  # Limit to top 50 files for brief context


def check_usage_limits(usage_file):
    """Prevents infinite billing loops."""
    if usage_file.exists():
        with open(usage_file) as f:
            data = json.load(f)
            if data["total_requests"] > data["daily_limit"]:
                print("[ARCHITECT] Daily limit reached. Stopping Singularity.")
                sys.exit(1)


def generate_tasks(project_name=None):
    paths = get_paths(project_name)
    print(f"[ARCHITECT] Analyzing project state (Project: {project_name or 'Root'})...")
    file_list = get_project_context()

    # The Prompt for the Architect
    prompt = f"""
You are the Lead Technical Architect for this project.
Your goal is Infinite Continuous Improvement.

Current Project Files:
{file_list}

INSTRUCTIONS:
1. Analyze the structure. Identify ONE impactful area for improvement (Refactoring, Tests, New Features, Documentation).
2. Generate a valid '{paths['task_file'].name}' content with 1 Stage and 2-4 Tasks.
3. Use specific file paths.
4. Output ONLY the raw Markdown content for the tasks file. No markdown code fences.
5. If a task depends on the completion of a previous task, explicitly annotate it with `@needs(Task description or keyword)` or `@needs(1-based line number)` at the end of the line description.

Format:
## Stage: [Name of Improvement]
- [ ] Task 1 description @context(file)
- [ ] Task 2 description @needs(Task 1 description)
"""

    # Call Gemini via agy_call wrapper.
    # NOTE: `agy --print` does not emit the response on stdout in headless mode
    # (see docs/AGY_PROGRAMMATIC.md). agy_complete() reads the persisted answer.
    try:
        # Ensure directory exists
        paths['prompt_file'].parent.mkdir(parents=True, exist_ok=True)

        with open(paths['prompt_file'], "w", encoding="utf-8") as f:
            f.write(prompt)

        # Run agy via the programmatic wrapper (resolves @file inline).
        from scripts.agy_call import agy_complete
        output = agy_complete(f"@{paths['prompt_file']}", model=GEMINI_MODEL, timeout=180)

        # Save to tasks file
        with open(paths['task_file'], "w", encoding="utf-8") as f:
            f.write("# Generated by Architect Agent\n\n" + output)

        print(f"[ARCHITECT] New tasks generated in {paths['task_file']}")

    except Exception as e:
        print(f"[ARCHITECT] Critical Error: {e}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(description="Architect Agent")
    parser.add_argument("--project", help="Project name (subfolder in .agent/)")
    args = parser.parse_args()

    paths = get_paths(args.project)
    check_usage_limits(paths['usage_file'])
    generate_tasks(args.project)


if __name__ == "__main__":
    main()
